
INSERT INTO `alumnos` (`id`, `nombre`, `primer_apellido`, `segundo_apellido`, `fecha_nacimiento`, `domicilio`, `poblacion`, `codigo_postal`, `telefono`, `email`) VALUES
(1, 'Ana', 'Valverde', 'Rioja', '2007-06-06', 'Calle del barco 34', 'Villacarrillo', 33019, '123456789', 'ana@ana.com'),
(2, 'José ', 'Minguez', 'Troli', '2004-06-09', 'Avenida de la Paz 43', '', 24766, '098765432', 'troli@troli.com'),
(3, 'Trampantojo', 'Espinoza', 'Villa', '2003-06-10', 'Plaza de las descalzas 456', 'Madrid', 28001, '987654321', 'villa@villa.com'),
(4, 'Alcantara', 'Mendez', 'Jiménez', '2004-06-17', 'Calle de los Urquijo 76', 'Andalucía', 45098, '567843290', 'alcantara.al@alcantara.com'),
(5, 'Ana', 'Valverde', 'Rioja', '2007-06-06', 'Calle del barco 34', 'Villacarrillo', 33019, '123456789', 'ana@ana.com'),
(6, 'José ', 'Minguez', 'Troli', '2004-06-09', 'Avenida de la Paz 43', '', 24766, '098765432', 'troli@troli.com'),
(7, 'Trampantojo', 'Espinoza', 'Villa', '2003-06-10', 'Plaza de las descalzas 456', 'Madrid', 28001, '987654321', 'villa@villa.com'),
(8, 'Alcantara', 'Mendez', 'Jiménez', '2004-06-17', 'Calle de los Urquijo 76', 'Andalucía', 45098, '567843290', 'alcantara.al@alcantara.com'),
(9, 'Ana', 'Valverde', 'Rioja', '2007-06-06', 'Calle del barco 34', 'Villacarrillo', 33019, '123456789', 'ana@ana.com'),
(10, 'José ', 'Minguez', 'Troli', '2004-06-09', 'Avenida de la Paz 43', '', 24766, '098765432', 'troli@troli.com'),
(11, 'Trampantojo', 'Espinoza', 'Villa', '2003-06-10', 'Plaza de las descalzas 456', 'Madrid', 28001, '987654321', 'villa@villa.com'),
(12, 'Alcantara', 'Mendez', 'Jiménez', '2004-06-17', 'Calle de los Urquijo 76', 'Andalucía', 45098, '567843290', 'alcantara.al@alcantara.com'),
(13, 'Ana', 'Valverde', 'Rioja', '2007-06-06', 'Calle del barco 34', 'Villacarrillo', 33019, '123456789', 'ana@ana.com'),
(14, 'José ', 'Minguez', 'Troli', '2004-06-09', 'Avenida de la Paz 43', '', 24766, '098765432', 'troli@troli.com'),
(15, 'Trampantojo', 'Espinoza', 'Villa', '2003-06-10', 'Plaza de las descalzas 456', 'Madrid', 28001, '987654321', 'villa@villa.com'),
(16, 'Alcantara', 'Mendez', 'Jiménez', '2004-06-17', 'Calle de los Urquijo 76', 'Andalucía', 45098, '567843290', 'alcantara.al@alcantara.com');

-- --------------------------------------------------------

INSERT INTO `cursos` (`id`, `titulo`, `estado`, `descripcion`, `imagen`, `new`, `tipo`) VALUES
(1, 'Aprende a programar con JavaScript, la tecnología de moda', 1, 'Esto es solo para un podo de texto pero casi siempre se pierde, y también es lo que se puede aprender.', 'subido649191a86bc2d.webp', 1, 'JavaScript'),
(2, 'Aprende uno de lenguajes de programación más potentes.', 1, 'Java es un lenguaje de programación de alto nivel, orientado a objetos y multiplataforma. Fue creado por Sun Microsystems en la década de 1990 y desde entonces ha sido ampliamente utilizado en el desarrollo de aplicaciones y sistemas.\r\n\r\nUna de las características principales de Java es su portabilidad, lo que significa que los programas escritos en este lenguaje pueden ejecutarse en diferentes sistemas operativos sin necesidad de realizar modificaciones significativas. Esto se logra mediante la compilación del código fuente a un formato intermedio llamado bytecode, que puede ser interpretado y ejecutado por la máquina virtual de Java (JVM).', 'subido6491923d99bdd.png', 1, 'JAVA'),
(3, 'Todo sobre el CSS para desarrollar cosas bonitas', 1, 'CSS (Cascading Style Sheets) es un lenguaje de hojas de estilo utilizado para describir y controlar la presentación de un documento HTML o XML. Proporciona una forma de definir el aspecto visual de una página web, incluyendo el diseño, los colores, las fuentes, los tamaños y otros aspectos relacionados con la apariencia. En CSS, se pueden aplicar reglas de estilo a elementos específicos del documento HTML utilizando selectores. Los selectores permiten identificar los elementos a los que se aplicarán las reglas de estilo, ya sea por su etiqueta, clase, identificador u otros atributos.', 'subido64919727280d7.png', 1, 'CSS'),
(4, 'Avanza con HTML', 1, 'Los elementos HTML permiten describir diferentes tipos de contenido, como encabezados, párrafos, enlaces, imágenes, listas, tablas, formularios y más. Cada elemento tiene un propósito específico y proporciona una estructura semántica para el contenido de la página.\r\nAdemás de los elementos, HTML también utiliza atributos para proporcionar información adicional sobre los elementos. Los atributos se agregan a las etiquetas y se utilizan para configurar características específicas, como el tamaño de una imagen o el destino de un enlace. Por ejemplo, el atributo \"src\" se utiliza en la etiqueta de imagen (\"<img>\") para especificar la ruta de la imagen.', 'subido6491c7e550210.webp', 0, 'HTML'),
(5, 'Conviértete en un Super JavaScript', 1, 'JavaScript es un lenguaje de programación de alto nivel, interpretado y orientado a objetos. Fue creado originalmente como un lenguaje de scripting para agregar interactividad a las páginas web, pero hoy en día también se utiliza en aplicaciones de servidor, aplicaciones móviles y otros entornos de desarrollo.', 'subido6491c8a564256.png', 1, 'JavaScript'),
(6, 'Otro curso de unos de los lenguajes mas populares', 1, 'Java se basa en el paradigma de programación orientada a objetos, lo que significa que los programas se estructuran en torno a objetos, que son instancias de clases. Las clases definen las propiedades y comportamientos de los objetos, y se pueden crear nuevas clases para extender y reutilizar el código existente.\r\n\r\nEl lenguaje Java ofrece una amplia biblioteca estándar (API) que proporciona un conjunto de clases y métodos predefinidos para realizar tareas comunes, como manipulación de archivos, acceso a bases de datos, comunicación en red, creación de interfaces gráficas de usuario, entre otros.', 'subido649192e574458.jpg', 1, 'Java'),
(7, 'Accede al mucho laboral con CSS', 1, 'Además de las reglas de estilo básicas, CSS proporciona una amplia gama de características avanzadas, como la capacidad de definir animaciones, transiciones, sombras, gradientes, diseños flexibles y responsivos, entre otros. Estas características permiten crear diseños web más dinámicos e interactivos.\r\nCSS se utiliza en conjunto con HTML para crear páginas web modernas y atractivas. Es ampliamente compatible con los navegadores web actuales y se actualiza regularmente con nuevas funcionalidades y mejoras.\r\nEn resumen, CSS es un lenguaje que permite controlar y personalizar la apariencia visual de los documentos HTML, brindando flexibilidad y capacidad de diseño a los desarrolladores web.', 'subido6491c727317e0.png', 0, 'CSS'),
(8, 'Super poder con HTML', 1, 'HTML también permite la inclusión de scripts y estilos en una página mediante etiquetas especiales, como \"<script>\" y \"<style>\". Estas etiquetas permiten agregar interactividad y aplicar estilos personalizados a los elementos HTML.\r\nEs importante destacar que HTML define la estructura y el significado del contenido, pero no se encarga de la presentación visual de la página. Para eso, se utiliza CSS (Cascading Style Sheets), que complementa HTML al definir los estilos y la apariencia visual de los elementos.', 'subido6491c8293779c.webp', 0, 'HTML'),
(9, 'Iniciación a la programación con JavaScript', 1, 'JavaScript se ejecuta en el navegador web del cliente, lo que permite interactuar con el contenido de la página web y realizar acciones en respuesta a eventos del usuario. Puede manipular el DOM (Document Object Model) para cambiar dinámicamente el contenido y la apariencia de una página, validar formularios, crear animaciones, realizar llamadas a servicios web y muchas otras funcionalidades interactivas.', 'subido6491c8eaa3aed.avif', 0, 'JavaScript'),
(10, 'Adquiere las competencias para programas con JAVA', 1, 'Además de su enfoque en la orientación a objetos, Java también incluye características como la gestión automática de memoria (a través del recolector de basura), la excepciones controladas, el manejo de hilos de ejecución para programación concurrente, la seguridad y la capacidad de realizar aplicaciones distribuidas mediante tecnologías como RMI (Remote Method Invocation) y Java EE (Enterprise Edition).\r\n\r\nJava ha sido utilizado en una amplia variedad de aplicaciones, desde desarrollo de aplicaciones de escritorio hasta aplicaciones web, móviles y empresariales. También ha sido ampliamente adoptado en el ámbito académico y en la industria de desarrollo de software debido a su facilidad de uso, robustez y comunidad de desarrolladores activa.', 'subido649193482662e.webp', 1, 'JAVA'),
(11, 'Curso avanzado de CSS', 1, 'Las reglas de estilo en CSS están compuestas por una propiedad y un valor. La propiedad define el aspecto que se desea modificar, como el color del texto o el tamaño de la fuente, y el valor especifica el contenido concreto de esa propiedad, como \"rojo\" o \"16px\".\r\n\r\nCSS también permite el uso de jerarquías y cascadas para aplicar estilos de manera selectiva. Esto significa que los estilos pueden heredarse de elementos padre a elementos hijos, y que se pueden aplicar múltiples estilos a un mismo elemento, resolviendo posibles conflictos de estilo mediante la cascada.', 'subido6491c6bd02b79.jpg', 0, 'CSS'),
(12, 'Aprende HTML', 1, 'HTML (HyperText Markup Language) es el lenguaje de marcado estándar utilizado para crear y estructurar el contenido de las páginas web. Es el lenguaje base de la web y proporciona una forma de describir la estructura y el significado de los elementos en un documento.\r\nEn HTML, los elementos se definen mediante etiquetas, que son palabras clave rodeadas por corchetes angulares (\"< >\"). Cada elemento tiene una etiqueta de apertura y una etiqueta de cierre, y el contenido se coloca entre estas etiquetas. Por ejemplo, la etiqueta \"<h1>\" se utiliza para indicar un encabezado de nivel 1, y se abrirá con \"<h1>\" y se cerrará con \"</h1>\".', 'subido6491c78e7ea77.jpg', 1, 'HTML');
